config/routes.rb
Shakespere::Application.routes.draw do

    resources :roles
	
  root to: 'roles#new'
  match '/create_table' => 'roles#create', :as => 'create_table'  
   match '/show_table',  to: 'roles#show'
  match '/reset_table',  to: 'roles#delete'
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :longest_speach, :name, :number_of_lines, :number_of_scenes, :scenes_percent

 before_save :default_values
  
   
  def default_values
	if (self.longest_speach == nil)
		self.longest_speach  = 0
		self.number_of_lines = 0
		self.number_of_scenes = 0
		self.scenes_percent = 0
	end
  end

  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/roles_controller.rb
require 'nokogiri'
require 'open-uri'


class RolesController < ApplicationController
   helper_method :sort_column, :sort_direction


 def new
	
  end

  def create
		scene_count = 0
		path = Rails.public_path + "/julius_caesar.xml"
		doc = Nokogiri::XML(open(path))
		
		###  Build initial roles db
		doc.xpath("//PERSONA").each do |persona| 
		
			 name = persona.text 
			 if  Role.find_by_name(name) == nil
				Role.create(name: name)
			end
				
		 end
		
		### fill in other role params
		doc.xpath("//SCENE").each do |scene| 
			 scene_count = scene_count+1
			names_in_scene = Hash.new
			
			
			scene.xpath('SPEECH').each do |speach| 
				 line_count = 0;
				 
				speach.xpath('SPEAKER').each do |sp|   ## handle case of multiples speakers in same speech
					#if speach.xpath('SPEAKER').index(sp.text) == 1  
						@speaker = sp.text
					#else
					#	@speaker = "All"
					#end
				 
					 if (@speaker != "All") 
						
						 speach.xpath('LINE').each do |line| 
							 line_count = line_count+1
						 end
						
						 role =  Role.find_by_name(@speaker)
						 role ||= Role.find(:first, :conditions => ["name LIKE ?", "%#{@speaker}"])  ## Handle case of partial name (e.g CATO, Young CATO)
						
						  if (names_in_scene.has_key?(@speaker) == FALSE)  
							names_in_scene[@speaker] = 1
						  end
						 
						
						 if role.longest_speach < line_count
							role.longest_speach = line_count
						 end
						 role.number_of_lines = role.number_of_lines + line_count
						 role.save
					 end
				end
			 end
			 
			 names_in_scene.each { |key,value| 
				
					role = Role.find_by_name(key)
					role ||= Role.find(:first, :conditions => ["name LIKE ?", "%#{key}"])
					role.number_of_scenes = role.number_of_scenes + 1
					role.save
			
			 }
			names_in_scene.clear
			
		 end
		 
		 for role in Role.all
			 role.scenes_percent = role.number_of_scenes.to_f/scene_count
			 role.save
		 end	
			
		render 'new'
  end
  
  def delete
		Role.delete_all
		render 'new'
  end
  
  def show
		@roles = Role.order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end
  
  
  private
  
  def sort_column
    Role.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
 def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shakespere</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/roles/new.html.erb
<!DOCTYPE html>


<body>
	<%= link_to "Create Table",  create_table_path %>
	<%= link_to "View Table",  show_table_path %>
	<%= link_to "Reset Table",  reset_table_path %>

</body>

app/views/roles/show.html.erb
<!DOCTYPE html>


<body>
	<script src="../assets/sorttable.js"></script>

	<%= form_tag show_table_path, :method => "get", :id => "roles_search" do %>

			<div id="sort-table">
					
				<%= hidden_field_tag :direction, params[:direction] %>
				<%= hidden_field_tag :sort, params[:sort] %>
				<table class="table">
					<thead>
							<td><%= sortable "name", "Role" %></td>
							<td><%= sortable "number_of_lines", "Number of lines" %></td>
							<td><%= sortable "longest_speach", "Longest speech (in lines)" %></td>
							<td><%= sortable "number_of_scenes", "Number of scenes" %></td>
							<td><%= sortable "scenes_percent", "Percent of scenes" %></td>
							
					</thead>
						<tbody>
						<% for role in @roles %>
							<tr>
								<td><%= role.name  %> </td>
								<td><%= role.number_of_lines  %> </td>
								<td><%= role.longest_speach  %> </td>
								<td><%= role.number_of_scenes  %> </td>
								<td><%= role.scenes_percent  %> </td>
							</tr>	
						<% end  %> 
					</tbody>
				</table>
				<%= will_paginate @roles %>
			</div>
			
		<% end  %> 
</body>